/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controller.Controller;
import javax.swing.*;
import java.awt.Dimension;
import java.util.Scanner;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.io.*;  
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.Color;
import java.awt.Font;



public class SearchScreen extends javax.swing.JFrame {

    /**
     * Creates new form SearchScreen
     */
    public SearchScreen(String from) {
        this.from = from;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("SEARCH FOR EMPLOYEE'S ID NUMBER:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });


        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setTitle("QUALITY INN AND SUITES HOTEL");
        setSize(1100, 600);
        setLayout(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        getContentPane().setBackground(Color.decode("#c8ebf4"));

        JLabel background;
        ImageIcon img = new ImageIcon("Logo.png");
        background = new JLabel("",img, JLabel.CENTER);
        background.setBounds(10,150, 700, 300);
        getContentPane().setBackground(Color.decode("#c8ebf4"));
        add(background); 


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addComponent(jButton2)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                    .addComponent(jButton2)
               .addContainerGap(98, Short.MAX_VALUE))
        );

       setSize(800,450);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextField1.getText().split(" ").length == 1){

            String id=jTextField1.getText();
            Controller con= new Controller();
            employeeRecord= con.searchEmployee(id);

            if (!employeeRecord.equals("Employee does not exists")){
        
                if (from.equals("editButton")){
                EditEmployeeScreen next = new EditEmployeeScreen(employeeRecord);
                next.setVisible(true);
                this.setVisible(false);
                }else{
                RentCollectionScreen next = new RentCollectionScreen(employeeRecord);
                next.setVisible(true);
                this.setVisible(false);
                }
            }else{
                ErrorHandling er = new ErrorHandling("Employee does not exists","Invalid Entry");
                er.setVisible(true);
            }
        }else{
         ErrorHandling er = new ErrorHandling("Enter an a valid name: 'firstname lastname","Invalid Entry");
         er.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        mainScreen next = new mainScreen();
        next.setVisible(true);
        this.setVisible(false);
    }
    private String from;
    private String employeeRecord;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
